custom-components/pyscript

- custom_components/pyscript/eval.py
I am trying to convert an AppDaemon app: https://github.com/basnijholt/home-assistant-config/blob/05ca9847edc2d68ae6429053d1de6e21db9c2848/appdaemon/apps/wake_up_light.py
> add bisect and colorsys to ALLOWED_IMPORTS

- custom_components/pyscript/__init__.py
- custom_components/pyscript/eval.py
I have implemented what I suggested in https://github.com/custom-components/pyscript/issues/8.
> add configuration option "allow_all_imports"

- README.md
- custom_components/pyscript/handler.py
> add function entity_ids that returns all entities

- custom_components/pyscript/trigger.py
Instead of getting datetime for todays sun event, force to get next
event, possibly being tomorrow.
Adjust now datetime in case next event is tomorrow.
Fix #18
> fix: wrong times for sunrise and sunset, when next occurrence is tomorrow

- .gitignore
- README.md
- custom_components/pyscript/__init__.py
- custom_components/pyscript/config_flow.py
- custom_components/pyscript/const.py
- custom_components/pyscript/manifest.json
- custom_components/pyscript/strings.json
- custom_components/pyscript/translations/en.json
- docs/configuration.rst
- info.md
- tests/test_config_flow.py
- tests/test_init.py
This change makes it possible to setup pyscript from the UI so a restart is not required (but `configuration.yaml` is still supported so there is no breaking change). I also updated the code to create the `<config/path>/pyscript` folder if it doesn't exist - not sure if there was an intentional reason why you required the user to create the folder but it seemed like an easy improvement (and otherwise, the user would have to create the pyscript folder *before* setting the integration up in the UI).
> Add config flow support

- custom_components/pyscript/config_flow.py
Should fix https://github.com/custom-components/pyscript/pull/31#issuecomment-706630554
> Fix pylint error from PR #31

- custom_components/pyscript/__init__.py
- custom_components/pyscript/config_flow.py
- custom_components/pyscript/const.py
- tests/test_config_flow.py
- tests/test_decorator_errors.py
- tests/test_function.py
- tests/test_init.py
- tests/test_jupyter.py
- tests/test_unique.py
This should resolve the issue we are discussing in #31. Since you said you can reproduce the issue @craigbarratt, can you test this and make sure it works? I would also test updating the config and doing a reload to make sure that the logic I changed works.
> Fix access to config data now that we are using config flow

- custom_components/pyscript/config_flow.py
- custom_components/pyscript/strings.json
- custom_components/pyscript/translations/en.json
- tests/test_config_flow.py
As discussed in the other PR thread, originally I had attempted to include references to HA's common strings, but that doesn't work for custom integrations so I'm providing the text here
> Fix config flow strings

- custom_components/pyscript/__init__.py
- custom_components/pyscript/config_flow.py
- custom_components/pyscript/eval.py
- custom_components/pyscript/strings.json
- custom_components/pyscript/translations/en.json
- tests/test_config_flow.py
- tests/test_unit_eval.py
As discussed in #39 , this change makes it possible to reload `allow_all_imports` via the reload service and also to configure it using the options menu for users who set up the entry through the UI (options will not work for users who do import, because when a user runs the reload service, and there is a mismatch between what's in the config and what was set in options, it would be impossible to know which one takes precedence. The config flow handles this gracefully and tells the user this if they attempt to access options for a config entry they defined in `configuration.yaml`).
I'm marking this as a draft because I discovered that my implementation won't work without https://github.com/home-assistant/core/pull/41875
I can change the implementation to avoid this, but it would be a less …
> Support reloading allow all imports through reload service and config entry options UI

- custom_components/pyscript/__init__.py
- custom_components/pyscript/config_flow.py
- custom_components/pyscript/const.py
- custom_components/pyscript/global_ctx.py
- custom_components/pyscript/strings.json
- custom_components/pyscript/translations/en.json
- docs/configuration.rst
- docs/reference.rst
- tests/test_config_flow.py
This PR adds a config parameter `hass_is_global` (default False), which if set provides `hass` as a global variable in all pyscript contexts.
@raman325 and @dlashua - I invited you to the forked repository.  Please review and feel free to push any changes to `craigbarratt/pyscript-hass-is-global`, or just comment here.
This will resolve #46.
> added hass_is_global config parameter

- custom_components/pyscript/__init__.py
- custom_components/pyscript/eval.py
- custom_components/pyscript/state.py
- custom_components/pyscript/trigger.py
- docs/reference.rst
With this change any states set by pyscript in the pyscript domain
will be persisted when home assistant next reboots.
For example when a script runs `pyscript.abc = 'foo'` then this value
will be persisted.
Fixes #47
> Persist pyscript.* states between home assistant restarts

- custom_components/pyscript/__init__.py
- custom_components/pyscript/const.py
- custom_components/pyscript/eval.py
- custom_components/pyscript/global_ctx.py
- tests/test_config_flow.py
- tests/test_unit_eval.py
Implements changes discussed in #42
> Unload scripts and unsubscribe from event listeners during entry unload

- custom_components/pyscript/function.py
- custom_components/pyscript/state.py
Test with:
```python
from homeassistant.core import Context
@state_trigger(['input_boolean.test_1'])
def test_state_trigger(**data):
log.info(data)
new_context = Context(parent_id=data['context'].id)
state.set('binary_sensor.test', 'on', context=new_context)
@state_trigger(['binary_sensor.test'])
def test_context_sent(**data):
log.info(data)
@event_trigger('PYSCRIPT_TEST')
def test_event_trigger(**data):
log.info(data)
new_context = Context(parent_id=data['context'].id)
event.fire('PYSCRIPT_TEST2', context=new_context)
@event_trigger('PYSCRIPT_TEST2')
def test_context_sent_event(**data):
log.info(data)
```
data logged by `test_context_sent_event` and `test_context_sent` should show `parent_id` of the received context.
> event.fire and state.set send context if provided

- custom_components/pyscript/function.py
- custom_components/pyscript/logbook.py
- custom_components/pyscript/state.py
- custom_components/pyscript/trigger.py
There might be a better way to do this instead of using `Function` like I have. However, it works.
A few things to note.
* The event fired before the function runs can be named anything we want. I chose "pyscript_running" and then realized Home Assistant uses "automation_triggered". This can be renamed by changing it in both `trigger.py` and `logbook.py`.
* While I have confirmed that `state.set()` is sending the correct context to the best of my knowledge, it seems that states set in this manner don't show up in the log book at all. The state still "sets" as expected, but there is no logbook entry. Therefore, all of the "context" code can be removed from `state.set()` if desired.
* I've left the original context as part of the trigger function kwargs. This way, pyscript users can still …
> Logbook Functionality

- custom_components/pyscript/__init__.py
- custom_components/pyscript/const.py
- tests/conftest.py
- tests/test_decorator_errors.py
- tests/test_function.py
- tests/test_init.py
- tests/test_jupyter.py
- tests/test_unique.py
As I mentioned in #66, it would be nice to be able to have `pyscript` install packages to be used in imports in cases where the user doesn't have the ability to install the packages themselves (in my case, I am using a Docker container for HomeAssistant so it would be cumbersome to install these requirements on every container rebuild).
I went ahead and implemented the functionality in this PR for your consideration. The way it works is that users can add a `requirements.txt` file to `pyscript/`. For any packages that are already installed, the version will be ignored so as not to mess with HomeAssistant functionality, and for any packages that aren't already installed, the package will be installed via a Home Assistant function. Since I am leveraging the Home Assistant function, the …
> Allow users to create a requirements.txt to install missing packages

- custom_components/pyscript/__init__.py
- tests/test_decorator_errors.py
- tests/test_function.py
- tests/test_init.py
- tests/test_jupyter.py
- tests/test_unique.py
`installed_version` also does IO from #68, this moves it to an executor job. Thanks @bdraco for catching this!
> Refactor logic for processing requirements.txt so all I/O operations happen in a single function

- custom_components/pyscript/function.py
- custom_components/pyscript/state.py
- docs/new_features.rst
- docs/reference.rst
- tests/test_function.py
- tests/test_state.py
I have created several functions in `pyscript` that make calls to other services. I could use `task.wait_until` to block execution until the service is finished running, but it seems more convenient to be able to specify that in the service call directly. As such, I have added support for the `blocking` and `limit` parameters which will give users more control over the service call behavior.
I am unsure how to test this - I'd be happy to add tests if you have some ideas on the best way to do that.
> Add support for service blocking

- custom_components/pyscript/state.py
This PR will prevent the error:
`TypeError: argument of type 'coroutine' is not iterable`
In the following code:
```
@time_trigger('startup')
def test():
a = state.get_attr('sun.sun')
for attrib in a:
log.info(attrib)
```
> await in deprecated get_attr

- custom_components/pyscript/requirements.py
> Install packaging module if not found

- custom_components/pyscript/function.py
> use list for unique_task2name

- custom_components/pyscript/__init__.py
- custom_components/pyscript/eval.py
- custom_components/pyscript/mqtt.py
- custom_components/pyscript/trigger.py
- docs/reference.rst
- tests/test_decorator_errors.py
This is a quick first attempt. The simplest of test scripts seems to work:
```python
@time_trigger('startup')
def mqtt_counter():
task.unique('mqtt_counter')
cnt = 0
while True:
cnt = cnt + 1
log.info(cnt)
mqtt.publish(topic='pyscript/test', payload=cnt)
mqtt.publish(topic='pyscript/testx10', payload=(cnt * 10))
task.sleep(1)
@mqtt_trigger('pyscript/test')
def mqtt_recv(**data):
log.info(f'got one {data}')
@mqtt_trigger('pyscript/test', 'topic == "notthis"')
def mqtt_never(**data):
log.info(f'this should never happen {data}')
@mqtt_trigger('pyscript/test', 'int(payload) % 2 == 0')
def mqtt_even(**data):
log.info(f'EVEN {data}')
@mqtt_trigger('pyscript/#')
def mqtt_wildcard(**data):
log.info(f'got one from wildcard {data}')
@mqtt_trigger('pyscript/test', 'payload == "5"')
def …
```
> add @mqtt_trigger

- custom_components/pyscript/function.py
This only corrects a misspelling.
> change repeaer to reaper

- custom_components/pyscript/trigger.py
> report errors in time_active

- docs/reference.rst
I couldn't find any mention of using vars from secrets.yaml in the docs so i added one in case some one else finds themselves in the same situation as me.
Related to #123
> Added an example of using secrets in the config

- custom_components/pyscript/eval.py
This PR allows for decorators from pyscript functions.
1) I have no idea if there's a better way to do this.
2) This has only limited testing performed
3) **FIXED** the decorator closures are evaluated every time the function is called. this differs from standard python. I believe this is just how pyscript works (creates a new EvalFunc object each time a method is called), though, perhaps @craigbarratt  can shed some light on a better place to put this that would work as expected. I can't think of any useful situations where evaluating the decorators every time would break a user's code, it's just not as efficient.
> WIP: pyscript decorators

- docs/reference.rst
Follow on to #173 . This reflects some of the service schema changes that are coming in 2021.3
> Update docs to reflect service description schema changes

- custom_components/pyscript/services.yaml
Updated `services.yaml` but wasn't sure if I got the required value right for all parameters of `jupyter_kernel_start`. Can you review and let me know which, if any, need to be updated?
These changes are not required but they do make calling the services from within the UI more friendly.
> update services.yaml schema to support 2021.3

- custom_components/pyscript/entity.py
- custom_components/pyscript/state.py
> fix for state.persist

- docs/reference.rst
There was an extra hash at the beginning of the HREF tag. The hash acted as an HTML anchor on the current page.
> Corrects the href back to HA's Dev Docs

- custom_components/pyscript/trigger.py
short test to prove the fix works:
```
@state_trigger("input_boolean.test_boolean", state_hold=1, kwargs={'test_kwarg': 123})
def tryouts(trigger_type=None, var_name=None, value=None, old_value=None, context=None, **kwargs):
log.debug(f"tryouts trigger_type: {trigger_type}, {kwargs}")
if kwargs.get('test_kwarg') == 123:
log.debug("after the fix")
else:
log.debug("before the fix")
```
> Fixes #374

- custom_components/pyscript/__init__.py
The Event class should have been imported from `homeassistant.core` (as per Frenck), and the current import breaks in 2023.8.  This change makes PyScript work properly in 2023.8.
> Fix import of Event

- custom_components/pyscript/eval.py
- custom_components/pyscript/function.py
- custom_components/pyscript/state.py
- Added argument "return_response" to be passed to the call to the underlying home assistant service API.
- Added "return" to several places so that executed service calls can actually return values.
- Added some convenience functionality so that the user does not need to explicitly specify arguments "return_response" or "blocking" when calling a service which returns a response.
The user can now call services and get responses back. This works for both ways of calling services, via service.call() and also when using the service name as a function. Users can now use the argument "return_response = True" when they are interested in getting a response like this:
`retval = service.call("mydomain", "myservice", return_response = True, ...)`
or
`retval = mydomain.myservice(return_response = …
> Added support for service responses when calling or creating services.

- custom_components/pyscript/eval.py
- custom_components/pyscript/state.py
- docs/reference.rst
Modifying StateVal according to homeassistant.core.State. Useful in complex logic: no need to store and pass entity_id.
Simplified example:
```python
def func(state):
num_seconds_ago = (dt.now(tz=timezone.utc) - state.last_changed).total_seconds()
if num_seconds_ago > 10:
light.toggle(entity_id=state.entity_id)
log.info(f"toggle {state.entity_id}")
```
> add virtual attribute StateVal.entity_id

- custom_components/pyscript/__init__.py
- custom_components/pyscript/entity.py
- custom_components/pyscript/eval.py
- custom_components/pyscript/trigger.py
- custom_components/pyscript/webhook.py
- docs/reference.rst
- tests/test_decorator_errors.py
- tests/test_jupyter.py
This PR closes #353  and adds a new webhook trigger defined as,
```python
@webhook_trigger(webhook_id, str_expr=None, local_only=True, methods={"POST", "PUT"}, kwargs=None)
def foo(payload):
pass
```
When looking into this, I was hoping that webhooks trigger events, but they unfortunately don't leading to this solution. I've been using this for about a week and it seems to be working stably.  I've added a few things to the tests to make sure things at least run. I'm not sure how to actually call a webhook in a test, but happy to do it if there is a way. 
I also added some documentation that hopefully covers everything.
Let me know if any changes or tweaks are needed!
> Webhook Trigger

- docs/installation.rst
- docs/overview.rst
- docs/reference.rst
- docs/tutorial.rst
This commit primarily builds out the HACS instructions on the installation doc page so that a new user who may not be familiar with HACS or have it installed will have enough background to get pyscript installed. Along with this, it synchronizes instructions regarding what to click with the button labels in Home Assistant (e.g., "Configuration ->" becomes "Settings -> Devices & services ->").
Secondary changes made address a few typographical issues in several documents. Only one change was made to a code snippet in 'tutorial.rst', relabeling 'pararm2' to 'param2'.
Note: At the end of 'tutorial.rst' there was a transition paragraph intended to introduce another section that would describe decorators/built-ins. This section was missing from the page, so I removed the transition paragraph. …
> docs: Build out HACS installation instructions

- custom_components/pyscript/state.py
adds `state.exist` classmethod to check whether an entity_id exists
very handy to check things exist before manipulating them to get rid of the exceptions
> adds state.exist classmethod to check whether an entity_id exists

- custom_components/pyscript/__init__.py
The Config class moved to homeassistant.core_config in 2024.11.0b0.
> Fix import of Config for HA 2024.11.0b0

- docs/reference.rst
The previous naming scheme was inconsistent.
> Cosmetic: make @mqtt_trigger example ids consistent

- docs/reference.rst
I just got bit by a couple things and wanted to contribute back to improve the documentation.
I think they are all minor changes or formatting and straight forward.
The biggest hurdle I had was trying to query the history, I was wanting yesterday's value, and everything in Home Assistant is geared around the most recent value.  In my case I was monitoring my car's TPMS and was wanting the leak rate, so now - yesterday.  I tried the Derivative sensor, but it does weighted averages for the time period, and since there's a large block of time each day that the car isn't available to get the pressure completely throws off the average leak rate.
```
instance = get_instance(hass)
future = await instance.async_add_executor_job(history.get_significant_states, hass, start, stop, ids)
```
I see the …
> docs/reference.rst @mqtt_trigger and callbacks

- custom_components/pyscript/config_flow.py
I looked at https://developers.home-assistant.io/blog/2024/11/12/options-flow/
and made the suggested changes.  Not sure what to do with the self._show_form = False on line 30 though.
> Attempt to fix config_entry warning
